#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');
const packageJsonPath = path.join(projectRoot, 'package.json');
const versionTsPath = path.join(projectRoot, 'src', 'version.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

if (typeof version !== 'string' || version.length === 0) {
  console.error('[sync-version] package.json version is missing or invalid.');
  process.exit(1);
}

const nextContent = `/**
 * Auto-generated by scripts/sync-version.cjs.
 * Do not edit manually.
 */
export const APP_VERSION = '${version}';
`;

const currentContent = fs.existsSync(versionTsPath)
  ? fs.readFileSync(versionTsPath, 'utf8')
  : '';

if (currentContent !== nextContent) {
  fs.writeFileSync(versionTsPath, nextContent, 'utf8');
  console.log(`[sync-version] Updated src/version.ts -> ${version}`);
} else {
  console.log(`[sync-version] src/version.ts is up to date (${version})`);
}
